### ISSUE TITLE
Error: Could not find or load main class core.Driver

### ISSUE THREAD

**Issue by Novian3002** [Valkryst/Schillsaver#18]
Downloaded the lastest release, marked it as exectuable and ran it from the terminal (java -jar Schillsaver.jar).
Running Ubuntu 17.04

**Comment by Valkryst** [comment]
Did you run it with *jav -jar Schillsaver.jar* or *java -jar Schillsaver.jar* and was there any error output to the terminal?

**Comment by Novian3002** [comment]
```
$ java -jar Schillsaver.jar 
Error: Could not find or load main class core.Driver

```

**Comment by Valkryst** [comment]
It's all good. I can't get a test image up and running right now, but I just uploaded a [new build](https://github.com/Valkryst/Schillsaver/releases/tag/11.1.0) directly from source for you to try.

All of the existing releases (6-11) are pretty old and outdated.

**Comment by Novian3002** [comment]
Weird, I still get the same error. Any info I could provide to help fix this?

**Comment by Valkryst** [comment]
Yup, there's a few things I can think of off the top of my head:

* Which JRE version are you running? You can type *java --version* to get this info.
* If you open the JAR file using 7z, or a similar program...
    * Does the *Driver.class* file exist within the *core* folder?
    * In a folder, called *MANIFEST* or something similar, there should be some files. If you pop open those files, what are the contents?

It could just be an issue with the manifest file pointing towards the wrong Driver location.

**Comment by Novian3002** [comment]
```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-2ubuntu1.17.04.3-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```
core/Driver.class exists

META-Inf/MANIFEST.MF:

```
Manifest-Version: 1.0
Main-Class: core.Driver
```

**Comment by Novian3002** [comment]
I switched to the offical Java release (https://launchpad.net/~webupd8team/+archive/ubuntu/java), that fixed it.
