### ISSUE TITLE
Add support for password protected Zip files.

### ISSUE THREAD

**Issue by Valkryst** [Valkryst/Schillsaver#30]

**Comment by whalehub** [comment]
There's a similar project called [BitGlitter](https://github.com/MarkMichon1/BitGlitter) that has support for AES-256 encryption. It might be worth having a look at their implementation of this feature.

**Comment by whalehub** [comment]
@Valkryst Any update on this?

**Comment by Valkryst** [comment]
@whalehub 
It's working locally at the moment, though there's still a bit of work left to do before I push the next release. If I have time, I'll see about wrapping things up over the next weekend or two

**Comment by Valkryst** [comment]
@whalehub 
It'll take some time to do the full rewrite that I've been planning, but I was able to get a working (at-least on my machine) build for you to try out.

Let me know how this works for you
[Schillsaver-2020.02.17-jar-with-dependencies.jar.zip](https://github.com/Valkryst/Schillsaver/files/4240135/Schillsaver-2020.02.17-jar-with-dependencies.jar.zip)

**Comment by whalehub** [comment]
@Valkryst Thanks, that seems to do the job.
