### ISSUE TITLE
Issue i am having.

### ISSUE THREAD

**Issue by jreoka** [Valkryst/Schillsaver#35]
I decided to mess around and run the ffmpeg command directly through ffmpeg without using Schillsaver.

I am able to convert an image into the pixels at my desired block size and resolution and successfully convert the image back.

The issue is that the original image is always a couple KB more than the converted image, and I'm not sure why.

Schillsaver doesn't do this but the direct command does for some reason. Am I perhaps doing something wrong?

**Comment by DillFrescott** [comment]
Just for clarification, the image is perfectly fine, aside from the slightly different size.
